src/Entity/Address.php
<?php

namespace App\Entity;

use App\Repository\AddressRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AddressRepository::class)
 */
class Address
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lastname;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $street;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $complement;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $country;

    /**
     * @ORM\Column(type="integer")
     */
    private $zip_code;

    /**
     * @ORM\Column(type="integer")
     */
    private $phone;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $company_name;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $shipping_comment;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $billing_address;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $shipping_address;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="addresses")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $email;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getStreet(): ?string
    {
        return $this->street;
    }

    public function setStreet(string $street): self
    {
        $this->street = $street;

        return $this;
    }

    public function getComplement(): ?string
    {
        return $this->complement;
    }

    public function setComplement(?string $complement): self
    {
        $this->complement = $complement;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(string $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function getZipCode(): ?int
    {
        return $this->zip_code;
    }

    public function setZipCode(int $zip_code): self
    {
        $this->zip_code = $zip_code;

        return $this;
    }

    public function getPhone(): ?int
    {
        return $this->phone;
    }

    public function setPhone(int $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getCompanyName(): ?string
    {
        return $this->company_name;
    }

    public function setCompanyName(?string $company_name): self
    {
        $this->company_name = $company_name;

        return $this;
    }

    public function getShippingComment(): ?string
    {
        return $this->shipping_comment;
    }

    public function setShippingComment(?string $shipping_comment): self
    {
        $this->shipping_comment = $shipping_comment;

        return $this;
    }

    public function getBillingAddress(): ?bool
    {
        return $this->billing_address;
    }

    public function setBillingAddress(?bool $billing_address): self
    {
        $this->billing_address = $billing_address;

        return $this;
    }

    public function getShippingAddress(): ?bool
    {
        return $this->shipping_address;
    }

    public function setShippingAddress(?bool $shipping_address): self
    {
        $this->shipping_address = $shipping_address;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVerified = false;

    /**
     * @ORM\OneToMany(targetEntity=Order::class, mappedBy="user")
     */
    private $orders;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $lastname;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date_birth;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $phone;

    /**
     * @ORM\Column(type="datetime")
     */
    private $registration_date;

    /**
     * @ORM\OneToMany(targetEntity=Address::class, mappedBy="user")
     */
    private $addresses;

    public function __construct()
    {
        $this->orders = new ArrayCollection();
        $this->addresses = new ArrayCollection();
        $this->registration_date = new \DateTime('now');
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    /**
     * @return Collection|Order[]
     */
    public function getOrders(): Collection
    {
        return $this->orders;
    }

    public function addOrder(Order $order): self
    {
        if (!$this->orders->contains($order)) {
            $this->orders[] = $order;
            $order->setUser($this);
        }

        return $this;
    }

    public function removeOrder(Order $order): self
    {
        if ($this->orders->contains($order)) {
            $this->orders->removeElement($order);
            // set the owning side to null (unless already changed)
            if ($order->getUser() === $this) {
                $order->setUser(null);
            }
        }

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getDateBirth(): ?\DateTimeInterface
    {
        return $this->date_birth;
    }

    public function setDateBirth(?\DateTimeInterface $date_birth): self
    {
        $this->date_birth = $date_birth;

        return $this;
    }

    public function getPhone(): ?int
    {
        return $this->phone;
    }

    public function setPhone(?int $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getRegistrationDate(): ?\DateTimeInterface
    {
        return $this->registration_date;
    }

    public function setRegistrationDate(\DateTimeInterface $registration_date): self
    {
        $this->registration_date = $registration_date;

        return $this;
    }

    /**
     * @return Collection|Address[]
     */
    public function getAddresses(): Collection
    {
        return $this->addresses;
    }

    public function addAddress(Address $address): self
    {
        if (!$this->addresses->contains($address)) {
            $this->addresses[] = $address;
            $address->setUser($this);
        }

        return $this;
    }

    public function removeAddress(Address $address): self
    {
        if ($this->addresses->contains($address)) {
            $this->addresses->removeElement($address);
            // set the owning side to null (unless already changed)
            if ($address->getUser() === $this) {
                $address->setUser(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->getFirstname().' '.$this->getLastname();
    }
}

templates/home/category.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    {% include 'home/news.html.twig' %}
    <div class="banner-category">
        <img class="d-block w-100" src="{{ asset('uploads/files/' ~ category.image) }}" alt="">
        <h1 class="centered">{{ category.name }}</h1>
    </div>
    <div class="container-fluid">
        <div class="row my-3 no-gutters justify-content-center">
            <nav class="navbar navbar-expand-lg navbar-light bg-white">
                <ul class="navbar-nav flex-row">
                    {% for subCateg in subCategories %}
                        <li class="nav-item mx-3">
                            <a class="nav-link font-weight-bold" href="{{ path('subCategory_index', {'id': subCateg.id}) }}">{{ subCateg.name }}</a>
                        </li>
                    {% endfor %}
                </ul>
            </nav>
        </div>
    </div>
    <div class="container">
        <div class="row no-gutters product-content">
            {% if items is empty %}
                <h3 class="text-center">Cette gamme de produit n'est pas disponible pour le moment !</h3>
            {% else %}
                {% for products in items %}
                    {% for product in products %}
                        <div class="card card-product mx-3 mb-5" style="width: 15rem;">
                            <a href="{{ path('product_index', {'id': product.id}) }}" class="subCateg ">
                                <img src="{{ asset('uploads/files/' ~ product.images[0]) }}" class="card-img-top card-product-image" alt="...">
                                <div class="card-body card-body-product my-2">
                                    <h5 class="card-title text-center">{{ product.name }}</h5>
                                    <p class="card-text text-center">{{ product.price }} €</p>
                                </div>
                            </a>
                        </div>
                    {% endfor %}
                {% endfor %}
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/home/contact.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    {% include 'home/news.html.twig' %}
    <div class="container mt-5 col-sm-10 col-md-6">
        <div class="card card-shadow bg-white mb-5">
            <div class="container px-4">
                <h1 class="mb-5 mt-3 text-center">Nous contacter</h1>
                {{ form_start(form) }}
                <div class="row">
                    <div class="col">{{ form_row(form.firstname) }}</div>
                    <div class="col">{{ form_row(form.lastname) }}</div>
                </div>
                {{ form_rest(form) }}
                <div class="col text-center">
                    <button class="btn btn-dark button-form mt-2 mb-4">{{ button_label|default('Envoyer') }}</button>
                </div>
                {{ form_end(form) }}
            </div>
        </div>
    </div>
{% endblock %}

templates/home/editProfile.html.twig
{% extends 'base.html.twig' %}

{% block title %}-Profile{% endblock %}

{% block body %}
    {% include 'home/news.html.twig' %}
    <div class="container col-md-6">
        <h1 class="text-center my-5">Modifier ton Profile</h1>
        {{ form_start(form) }}
        {{ form_widget(form) }}
        {{ form_rest(form) }}
        <button class="btn btn-success">{{ button_label|default('Modifier') }}</button>
        {{ form_end(form) }}
    </div>
{% endblock %}

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    {% include 'home/news.html.twig' %}
    <div id="carouselExampleIndicators" class="carousel slide home-carousel" data-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="{{ asset('uploads/files/' ~ banners[0].image) }}" class="d-block w-100" alt="...">
                <div class="carousel-caption ">
                    <h2 class="font-weight-bold">{{ banners[0].title }} </h2>
                    <p>{{ banners[0].description | raw }}</p>
                </div>
            </div>
            {% for banner in banners | slice(1) %}
            <div class="carousel-item">
                <img src="{{ asset('uploads/files/' ~ banner.image) }}" class="d-block w-100" alt="...">
                <div class="carousel-caption ">
                    <h2 class="font-weight-bold">{{ banner.title }} </h2>
                    <p>{{ banner.description | raw }}</p>
                </div>
            </div>
            {% endfor %}
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
    <div class="container mt-3">
        <div class="row no-gutters">
            {% for category in categories %}
                <div class="col-md-6 col-lg-4">
                    <a href="{{ path('category_index', {'id': category.id}) }}" class="box">
                        <h3 class="text-center font-weight-bold centered">{{ category.name }}</h3>
                        <img class="mt-3 img-fluid" src="{{ asset('uploads/files/' ~ category.images[0].image) }}" width="360px" height="300px" alt="{{ category.name }}">
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/home/news.html.twig
{% if news.active == 1 %}
    <div class="news-defil pt-2 ">
        <p class="lead">
            {{ news.info }}
        </p>
    </div>
{% endif %}

templates/home/product.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    {% include 'home/news.html.twig' %}
    <div class="container mt-3 d-flex justify-content-center">
        {% for category, messages in app.flashes %}
            {% for message in messages %}
                <div class="text-center card-shadow col-6 alert alert-{{ category }}">
                    <p>{{ message }}</p>
                    <a href="{{ path('cart_index') }}" class="btn btn-dark">Voir mon panier !</a>
                </div>
            {% endfor %}
        {% endfor %}
    </div>
    <div class="container mt-3 mb-5">
        <h3 class="text-center">
            <a class="text-dark" href="{{ path('subCategory_index', {'id': subCateg.id}) }}">{{ subCateg.name }}</a> /
            <a class="text-dark" href="{{ path('subCategory2_index', {'id': subCateg2.id}) }}">{{ subCateg2.name }}</a>
        </h3>
    </div>
    <div class="container mt-3 d-md-flex ">
        <div id="carouselExampleIndicators" class="carousel slide mb-4 col-md-6" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carouselExampleIndicators" data-slide-to="{{ product.images[0].id }}" class="active"></li>
                {% for image in product.images %}
                <li data-target="#carouselExampleIndicators" data-slide-to="{{ image.id }}"></li>
                {% endfor %}
            </ol>
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img src="{{ asset('uploads/files/' ~ product.images[0]) }}" class="d-block w-100" alt="...">
                </div>
                {% for image in product.images %}
                <div class="carousel-item">
                    <img src="{{ asset('uploads/files/' ~ image) }}" class="d-block w-100" alt="...">
                </div>
                {% endfor %}
            </div>
            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
        <div class="product-description ml-5 col-md-5">
            <h1>{{ product.name }}</h1>
            <h3>{{ product.price }} €</h3>
            {% if sizes != null %}
            <form method="post">
                <div class="form-group">
                    <label for="exampleFormControlSelect1">Tailles :</label>
                    <select class="form-control w-25" name="size" id="exampleFormControlSelect1">
                    {% for size in sizes %}
                        <option value="{{ size }}">{{ size }}</option>
                    {% endfor %}
                    </select>
                </div>
                <p class="mt-3">{{ product.description | raw }}</p>
                <button type="submit" class="btn btn-dark mt-3">Ajouter au Panier</button>
            </form>
            {% else %}
            <p class="mt-3">{{ product.description | raw }}</p>
            <a href="{{ path('cart_add', {'id': stockId}) }}" class="btn btn-dark mt-3">Ajouter au Panier</a>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/home/profile.html.twig
{% extends 'base.html.twig' %}

{% block title %}-Mon Profile{% endblock %}

{% block body %}
{% include 'home/news.html.twig' %}
<div class="container mt-5">
    <h1 class="text-center title">Mon Profile</h1>
    <a class="float-right" href="{{ path('app_logout') }}">Déconnexion</a>
    <div class="row mt-5 justify-content-between">
        <div class="col-md-5 mt-5">
            <h3>Mes commandes</h3>
            <a class="btn btn-dark my-3" data-toggle="collapse" href="#myOrders" role="button" aria-expanded="false" aria-controls="myOrders">Voir mes commandes</a>
            <div class="collapse" id="myOrders">
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">Date</th>
                            <th scope="col">Status</th>
                            <th scope="col">Référence</th>
                            <th scope="col">Détails</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for order in orders %}
                        <tr>
                            <td>{{ order.date | date("d/m/Y") }}</td>
                            <td>{{ order.status }}</td>
                            <td>{{ order.reference }}</td>
                            <td>
                                <a data-toggle="collapse" href="#{{ order.reference }}" role="button" aria-expanded="false" aria-controls="{{ order.reference }}">Détails</a>
                            </td>
                        </tr>
                        <tr class="collapse" id="{{ order.reference }}">
                            <td colspan="5">
                                <div class="card card-body">
                                    <table class="table">
                                        <thead>
                                        <tr>
                                            <th>Produit</th>
                                            <th>Quantité</th>
                                            <th>Prix ( € )</th>
                                            <th>Total (TTC)</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        {% for item in items %}
                                            <tr>
                                                <td><a href="{{ path('product_index', {'id': item.product.id}) }}">{{ item.product.name }}</a></td>
                                                <td>{{ item.quantity }}</td>
                                                <td>{{ item.product.price }}</td>
                                                <td>{{ item.quantity * item.product.price }} €</td>
                                            </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <div class="col-md-6 mt-5 card card-shadow">
            <div class="card-body">
                <div class="d-flex justify-content-center">
                    <h3 class="text-center mb-5 font-weight-bold">Informations</h3>
                    <a class="text-dark ml-3" href="{{ path('profile_edit', {'id': user.id}) }}"><i class="fas fa-pencil-alt"></i></a>
                </div>
                <div class="d-flex justify-content-between">
                    <div>
                        <p><strong>Nom :</strong> {{ user.firstname }}</p>
                        <p><strong>Prénom :</strong> {{ user.lastname }}</p>
                        <p><strong>Email :</strong> {{ user.email }}</p>
                    </div>
                    <div>
                        <p><strong>Naissance :</strong> {{ user.dateBirth }}</p>
                        <p><strong>Téléphone :</strong> {{ user.phone }}</p>
                    </div>
                </div>
                <hr>
                <div class="d-flex mt-5 justify-content-between">
                    <div>
                        <h5 class="mb-3 font-weight-bold">Adresse de livraison :</h5>
                        {% if shippingAddress != null %}
                            <p>{{ shippingAddress.firstname }} {{ shippingAddress.lastname }}</p>
                            <p>{{ shippingAddress.street }}</p>
                            <p>{{ shippingAddress.complement }}</p>
                            <p>{{ shippingAddress.zipCode }}</p>
                            <p>{{ shippingAddress.city }}</p>
                            <p>{{ shippingAddress.country }}</p>
                            <p>{{ shippingAddress.phone }}</p>
                            <a href="{{ path('shippingAddress_edit', {'id': shippingAddress.id}) }}">Modifier</a>
                        {% else %}
                        <a class="btn btn-dark" href="{{ path('address_newShipping') }}"><i class="fas fa-plus"></i> Adresse</a>
                        {% endif %}
                    </div>
                    <div>
                        <h5 class="mb-3 font-weight-bold">Adresse de facturation :</h5>
                        {% if billingAddress != null %}
                            <p>{{ billingAddress.firstname }} {{ billingAddress.lastname }}</p>
                            <p>{{ billingAddress.street }}</p>
                            <p>{{ billingAddress.complement }}</p>
                            <p>{{ billingAddress.zipCode }}</p>
                            <p>{{ billingAddress.city }}</p>
                            <p>{{ billingAddress.country }}</p>
                            <p>{{ billingAddress.phone }}</p>
                            <a href="{{ path('billingAddress_edit', {'id': billingAddress.id}) }}">Modifier</a>
                        {% else %}
                            <a class="btn btn-dark" href="{{ path('address_newBilling') }}"><i class="fas fa-plus"></i> Adresse</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/home/search.html.twig
{% extends 'base.html.twig' %}


{% block body %}
{% include 'home/news.html.twig' %}
<div class="container mt-5">
    <div class="row flex-column justify-content-center">
        <h3 class="text-center font-weight-bold">Chercher un produit</h3>
        <div class="d-flex mb-5 mt-3 justify-content-center">
            <form method="post" class="form-inline my-2 my-lg-0 search">
                <input class="form-control mr-sm-2" name="name" type="search" placeholder="Search" aria-label="Search">
                <button class="btn my-2 my-sm-0" type="submit"><i class="fas fa-search"></i></button>
            </form>
        </div>
    </div>
    <div class="row">
        {% if products is defined %}
            {% for product in products %}
                <div class="card card-product mx-3 mb-5" style="width: 15rem;">
                    <a href="{{ path('product_index', {'id': product.id}) }}" class="subCateg ">
                        <img src="{{ asset('uploads/files/' ~ product.images[0]) }}" class="card-img-top card-product-image" alt="...">
                        <div class="card-body card-body-product my-2">
                            <h5 class="card-title text-center">{{ product.name }}</h5>
                            <p class="card-text text-center">{{ product.price }} €</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        {% else %}
            <p>Nous n'avons rien trouvé !</p>
        {% endif %}
    </div>
</div>
{% endblock %}

templates/home/subCategory.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    {% include 'home/news.html.twig' %}
    <div class="banner-category">
        <img class="d-block w-100" src="https://i.postimg.cc/T2CMZyV2/Webp-net-resizeimage-1.jpg" alt="">
        <h1 class="centered">{{ subCateg.name }}</h1>
    </div>
    <div class="container-fluid">
        <div class="row my-3 no-gutters justify-content-center">
            <nav class="navbar navbar-expand-lg navbar-light bg-white">
                <ul class="navbar-nav flex-row">
                    {% for subCateg in subCategories %}
                        <li class="nav-item mx-3">
                            <a class="nav-link font-weight-bold" href="{{ path('subCategory_index', {'id': subCateg.id}) }}">{{ subCateg.name }}</a>
                        </li>
                    {% endfor %}
                </ul>
            </nav>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row no-gutters justify-content-between">
            <div class="col-md-2 d-none d-md-block">
                <ul class="list-group list-group-flush">
                    {% for subCateg2 in subCategs2 %}
                        <li class="list-group-item"><a class="text-dark" href="{{ path('subCategory2_index', {'id': subCateg2.id}) }}">{{ subCateg2.name }}</a></li>
                    {% endfor %}
                </ul>
            </div>
            <div class="col-sm-2 d-md-none mb-3">
                <a class="btn btn-dark mb-2" data-toggle="collapse" href="#Categories" role="button" aria-expanded="false" aria-controls="Categories">
                    Catégories
                </a>
                <div class="collapse" id="Categories">
                    <div class="card card-shadow card-body">
                        <ul class="list-group list-group-flush">
                            {% for subCateg2 in subCategs2 %}
                                <li class="list-group-item"><a class="text-dark" href="{{ path('subCategory2_index', {'id': subCateg2.id}) }}">{{ subCateg2.name }}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        {% if products is empty %}
            <div class="col-md-9 d-flex product-content">
                <h3 class="text-center">Cette gamme de produit n'est pas disponible pour le moment !</h3>
            </div>
        {% else %}
            <div class="row col-md-10 product-content">
            {% for product in products %}
                <div class="card card-product mx-3 mb-5" style="width: 15rem;">
                    <a href="{{ path('product_index', {'id': product.id}) }}" class="subCateg ">
                    <img src="{{ asset('uploads/files/' ~ product.images[0]) }}" class="card-img-top card-product-image" alt="...">
                    <div class="card-body card-body-product my-2">
                        <h5 class="card-title text-center">{{ product.name }}</h5>
                        <p class="card-text text-center">{{ product.price }} €</p>
                    </div>
                    </a>
                </div>
            {% endfor %}
            </div>
        {% endif %}
        </div>
    </div>
{% endblock %}