src/Entity/Address.php
<?php

namespace App\Entity;

use App\Repository\AddressRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AddressRepository::class)
 */
class Address
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lastname;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $street;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $complement;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $country;

    /**
     * @ORM\Column(type="integer")
     */
    private $zip_code;

    /**
     * @ORM\Column(type="integer")
     */
    private $phone;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $company_name;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $shipping_comment;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $billing_address;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $shipping_address;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="addresses")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $email;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getStreet(): ?string
    {
        return $this->street;
    }

    public function setStreet(string $street): self
    {
        $this->street = $street;

        return $this;
    }

    public function getComplement(): ?string
    {
        return $this->complement;
    }

    public function setComplement(?string $complement): self
    {
        $this->complement = $complement;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(string $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function getZipCode(): ?int
    {
        return $this->zip_code;
    }

    public function setZipCode(int $zip_code): self
    {
        $this->zip_code = $zip_code;

        return $this;
    }

    public function getPhone(): ?int
    {
        return $this->phone;
    }

    public function setPhone(int $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getCompanyName(): ?string
    {
        return $this->company_name;
    }

    public function setCompanyName(?string $company_name): self
    {
        $this->company_name = $company_name;

        return $this;
    }

    public function getShippingComment(): ?string
    {
        return $this->shipping_comment;
    }

    public function setShippingComment(?string $shipping_comment): self
    {
        $this->shipping_comment = $shipping_comment;

        return $this;
    }

    public function getBillingAddress(): ?bool
    {
        return $this->billing_address;
    }

    public function setBillingAddress(?bool $billing_address): self
    {
        $this->billing_address = $billing_address;

        return $this;
    }

    public function getShippingAddress(): ?bool
    {
        return $this->shipping_address;
    }

    public function setShippingAddress(?bool $shipping_address): self
    {
        $this->shipping_address = $shipping_address;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }
}

templates/pdf/invoice.html.twig
<html>
<head>
    <meta charset="UTF-8">
    <title>Invoice</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <style>
        body {
            font-size: 80%;
        }
        p {
            line-height: 70%;
        }
        .shipping {
            margin-left: 400px;
        }
        .block{
            margin-bottom: 30px;
        }
        .list-prod{
            margin-top: -100px;
        }
    </style>
</head>
<body>

<div class="container-fluid">
    <h2 class="mb-5">NewGenerationSupreme</h2>
    <p class="mt-5"><strong>Référence de commande:</strong> {{ order.reference }}</p>
    <p class="block"><strong>Date :</strong> {{ order.date | date("d/m/Y") }}</p>
    <div class="row">
        <div>
            <p><strong>ADRESSES DE FACTURATION :</strong></p>
            <p><strong>Nom: </strong>{{ infoClientB.firstname }}</p>
            <p><strong>Prénom: </strong>{{ infoClientB.lastname }}</p>
            <p><strong>Entreprise: </strong>{{ infoClientB.companyName }}</p>
            <p><strong>Adresse: </strong>{{ infoClientB.street }}</p>
            <p>{{ infoClientB.complement }}</p>
            <p>{{ infoClientB.zipCode }} {{ infoClientB.city }}</p>
            <p>{{ infoClientB.country }}</p>
        </div>
        <div class="shipping">
            <p><strong>ADRESSES DE LIVRAISON :</strong></p>
            <p><strong>Nom: </strong>{{ infoClientS.firstname }}</p>
            <p><strong>Prénom: </strong>{{ infoClientS.lastname }}</p>
            <p><strong>Entreprise: </strong>{{ infoClientS.companyName }}</p>
            <p><strong>Adresse: </strong>{{ infoClientS.street }}</p>
            <p>{{ infoClientS.complement }}</p>
            <p>{{ infoClientS.zipCode }} {{ infoClientS.city }}</p>
            <p>{{ infoClientS.country }}</p>
        </div>
    </div>
    <div class="row ">
        <table class="table table-striped list-prod">
            <thead>
                <tr>
                    <th>Produit</th>
                    <th>Quantité</th>
                    <th>Prix ( € )</th>
                    <th>Total (TTC)</th>
                </tr>
            </thead>
            <tbody>
            {% for item in items %}
                <tr>
                    <td>{{ item.stockProduct.product.name }}{% if item.stockProduct.size != null %} - {{ item.stockProduct.size }}{% endif %}</td>
                    <td>{{ item.quantity }}</td>
                    <td>{{ item.stockProduct.product.price}}</td>
                    <td>{{ item.quantity * item.stockProduct.product.price }} €</td>
                </tr>
            {% endfor %}
            <tr>
                <td>Livraison : {{ shipping.type }}</td>
                <td></td>
                <td></td>
                <td>{{ shipping.price }} €</td>
            </tr>
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="3" class="text-right">Total (TTC) : </td>
                    <td>{{ total }} €</td>
                    <td></td>
                </tr>
            </tfoot>
        </table>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>